using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class TextureSender : MonoBehaviour
{

    public TexturePainter texturePainter; // –ü–æ—Å–∏–ª–∞–Ω–Ω—è –Ω–∞ –∫–æ–º–ø–æ–Ω–µ–Ω—Ç TexturePainter
    public TextureSenderClient textureSenderClient; // –ü–æ—Å–∏–ª–∞–Ω–Ω—è –Ω–∞ –∫–æ–º–ø–æ–Ω–µ–Ω—Ç TextureSenderClient

    public bool sendCustomTexture = false; // –ü—Ä–∞–ø–æ—Ä–µ—Ü—å –¥–ª—è –≤—ñ–¥–ø—Ä–∞–≤–∫–∏ —Ç–µ–∫—Å—Ç—É—Ä–∏


    // Update is called once per frame
    void Update()
    {
        if (sendCustomTexture)
        {
            sendCustomTexture = false; // –°–∫–∏–¥–∞—î–º–æ –ø—Ä–∞–ø–æ—Ä–µ—Ü—å –ø—ñ—Å–ª—è –≤—ñ–¥–ø—Ä–∞–≤–∫–∏
            SendTexture();
        }
    }
    
    public void SendTexture()
    {
        if (texturePainter == null || textureSenderClient == null)
        {
            Debug.LogError("üö´ TextureSender: –ù–µ –≤–∫–∞–∑–∞–Ω—ñ –∫–æ–º–ø–æ–Ω–µ–Ω—Ç–∏ TexturePainter –∞–±–æ TextureSenderClient.");
            return;
        }

        Texture2D toSend = texturePainter.GetPaintedTextureCopy();
        textureSenderClient.SendTexture(toSend);
    }

}
